//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignatureTable
    {
        public int id { get; set; }
        public string author { get; set; }
        public string title { get; set; }
        public string subject { get; set; }
        public string keyword { get; set; }
        public string reason { get; set; }
        public string email { get; set; }
        public string location { get; set; }
        public string pdfName { get; set; }
        public string certName { get; set; }
        public string password { get; set; }
        public string requestorId { get; set; }
        public string issuerId { get; set; }
        public string status { get; set; }
    }
}
